# Generated by Django 4.2.7 on 2023-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(null=True, upload_to='profiles/')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('science fiction', 'Science Fiction'), ('thriller', 'Thriller')], max_length=15)),
                ('release_year', models.IntegerField()),
                ('resume', models.TextField(max_length=1000)),
            ],
        ),
    ]
