# Generated by Django 4.2.7 on 2023-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('science fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('non-fiction', 'Non-Fiction')], max_length=15),
        ),
    ]
