# Generated by Django 4.2.7 on 2023-11-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='technical_specifications',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
